name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  clientSecret:
    required: true
    description: 'Client secret of oauth2 client application'
  clientId:
    required: true
    description: 'Client id of oauth2 client application'
  redirectUri:
    required: true
    description: 'Redirect uri of oauth2 client application'
  credential_json:
    required: true
    description: 'credential.json with refresh_token and scope https://www.googleapis.com/auth/drive.readonly'
  q:
    required: true
    description: 'Query string to search for files and folders'
  path:
    required: false
    description: 'Path to download files default to working directory'
runs:
  using: 'node12'
  main: 'dist/index.js'
